/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/vizitka_remastered.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vizitka_remastered.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_low_1.geometry} material={materials.DefaultMaterial} />
    </group>
  )
}

useGLTF.preload('/vizitka_remastered.glb')
